# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 287e906bd8dc6022273d0e6b67196e0937073aa2dc5aab634ae3015eb4c696d58615837a51379937a1ebbae910d3867689fd0bfa5820ee2b19bf54b2b89cab03

test:
  secret_key_base: d2d6de1a9a28574ebb155cbeadee3b1f3963594fc6f7d757f7ac99c29bc344bc1fe27466a80f712374a33fc67b3a9062b691e37b4744002a6613940636235349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
